### ISSUE TITLE
Less Variables from imported files

### ISSUE THREAD

**Issue by zslabs** [AtomLinter/linter-less#6]
Hi,
Thanks for creating this! I've come across a bit of an intermittent issue. 

    // global.less
	.bt-results__page-header {

		@media (max-width: @breakpoint-small-max) {
			display: none;
		}
	}

Throws the following error:

    variable @breakpoint-small-max is undefined

Even though this variable is defined. It's being pulled in via `bower` that is compiled along with the aforementioned `global.less` 

    // app.less

    @import "bower_components/lib/variables.less";
    @import "global.less";

It doesn't seem to always happen with that specific variable, but it has popped up every so often with others. Any points would be greatly appreciated. Thanks!

**Comment by hd-deman** [comment]
it's happened because Linter copy your file to tmp dir before lint it.

**Comment by josa42** [comment]
Actually I don't think this happens because the file is copied. The current path is passed to `lessc`, so the imports should be resolved correctly.

But when you are editing  `global.less` the variables are not imported, because the import happens in `app.less`.

`lessc` is executed like that:

```
lessc --include-path=/Users/josa/less-test /tmp/path/global.less
NameError: variable @breakpoint-small-max is undefined in /Users/josa/less-test/global.less on line 4, column 24:
3
4     @media (max-width: @breakpoint-small-max) {
5         display: none;
```

Right now I cannot think of a good solution for this.

**Comment by josa42** [comment]
I added an option to "ignore undefined variables", which is off by default but can be activated in the settings of linter-less. Let me know if that resolves the issue for you.

**Comment by zslabs** [comment]
Honestly not sure if that's the best option - because valid "undefined variables" would then show as being alright. I do understand the complexities of lessc not being able to handle the imports, but don't want to negate the rest of the usefulness of that feature.

**Comment by josa42** [comment]
The problem is not that lessc is not being able to handle the imports. In your example global.less in imported in app.less. So when you lint global.less the variables are not imported.

Another solution I came up with is to add the option to hint global variables in a comment, similar to JSHInt.

Maybe like that:

```
// global @a
// global @b
```

**Comment by josa42** [comment]
I opened a new issue for this: 12

**Comment by zslabs** [comment]
Cool thanks. While obviously not 100% ideal, I'm alright with following that convention until something changes on the lessc side of things.
